# Generated by Django 5.2.4 on 2025-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
