# Generated by Django 5.2.4 on 2025-07-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0003_ownedbadge"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnBadge",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=100)),
                ("date_awarded", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="own_badges",
                        to="badges.badge",
                    ),
                ),
            ],
            options={
                "unique_together": {("badge", "user_id")},
            },
        ),
        migrations.DeleteModel(
            name="OwnedBadge",
        ),
    ]
