# Generated by Django 5.2.4 on 2025-08-13 22:00

from django.db import migrations, models

import badges.models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0004_ownbadge_delete_ownedbadge"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="secret",
            field=models.CharField(
                default=badges.models.generate_secret, max_length=100, null=True
            ),
        ),
    ]
