# Generated by Django 5.2.4 on 2025-08-13 22:02

import secrets

from django.db import migrations


def gen_secret(apps, schema_editor):
    Badge = apps.get_model("badges", "Badge")
    for row in Badge.objects.all():
        row.secret = secrets.token_urlsafe(16)
        row.save(update_fields=["secret"])


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0005_badge_secret"),
    ]

    operations = [
        migrations.RunPython(gen_secret, reverse_code=migrations.RunPython.noop),
    ]
