# Generated by Django 5.2.4 on 2025-08-13 22:02

from django.db import migrations, models

import badges.models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0006_gen_badge_secrets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="secret",
            field=models.CharField(
                default=badges.models.generate_secret, max_length=100, unique=True
            ),
        ),
    ]
