# Generated by Django 5.2.4 on 2025-08-15 14:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0007_unique badge secret"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={"verbose_name": "Badge", "verbose_name_plural": "Badges"},
        ),
        migrations.AlterField(
            model_name="badge",
            name="secret",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="badge",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("secret"),
                name="unique_badge_secret",
            ),
        ),
    ]
