# Generated by Django 5.2.4 on 2025-08-19 16:56

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0008_alter_badge_options_alter_badge_secret_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge Code",
                "verbose_name_plural": "Badge Codes",
            },
        ),
        migrations.RemoveConstraint(
            model_name="badge",
            name="unique_badge_secret",
        ),
        migrations.RenameField(
            model_name="ownbadge",
            old_name="date_awarded",
            new_name="awarded_at",
        ),
        migrations.RemoveField(
            model_name="badge",
            name="secret",
        ),
        migrations.AddField(
            model_name="badgecode",
            name="badges",
            field=models.ManyToManyField(related_name="badge_codes", to="badges.badge"),
        ),
        migrations.AddConstraint(
            model_name="badgecode",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"), name="unique_badge_code"
            ),
        ),
    ]
