# Generated by Django 5.2.4 on 2025-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0009_badgecode_remove_badge_unique_badge_secret_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["name"],
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.AddField(
            model_name="badge",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
