# Generated by Django 5.2.4 on 2025-09-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0010_alter_badge_options_badge_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Badge Category",
                "verbose_name_plural": "Badge Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="badge",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="badges.badgecategory",
            ),
        ),
    ]
