# Generated by Django 5.2.4 on 2025-09-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0011_badgecategory_badge_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeCodeLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("badge_code", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge Code Log",
                "verbose_name_plural": "Badge Code Logs",
                "ordering": ["-used_at"],
            },
        ),
    ]
