# Generated by Django 5.2.4 on 2025-07-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="conferences/"),
        ),
    ]
