# Generated by Django 5.2.4 on 2025-07-17 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0002_conference_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conference",
            options={
                "ordering": ["name"],
                "verbose_name": "Conference",
                "verbose_name_plural": "Conferences",
            },
        ),
        migrations.AlterModelOptions(
            name="conferencetopic",
            options={
                "ordering": ["name"],
                "verbose_name": "Conference Topic",
                "verbose_name_plural": "Conference Topics",
            },
        ),
        migrations.AlterModelOptions(
            name="conferencetype",
            options={
                "ordering": ["name"],
                "verbose_name": "Conference Type",
                "verbose_name_plural": "Conference Types",
            },
        ),
    ]
