# Generated by Django 5.2.4 on 2025-08-15 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0003_alter_conference_options_and_more"),
        ("rooms", "0002_populate_data"),
        ("speakers", "0005_alter_speaker_bio_alter_speaker_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conferences",
                to="rooms.room",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conference",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conferences",
                to="speakers.speaker",
            ),
        ),
    ]
