# Generated by Django 5.2.4 on 2025-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="instagram",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="linked_in",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
