# Generated by Django 5.2.4 on 2025-08-15 15:55

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    Room = apps.get_model("rooms", "Room")

    data = [
        {"id": 1, "name": "A1", "building": "Studium 6"},
        {"id": 2, "name": "A2", "building": "Studium 6"},
        {"id": 3, "name": "A3", "building": "Studium 6"},
        {"id": 4, "name": "A4", "building": "Studium 6"},
        {"id": 5, "name": "A5", "building": "Studium 6"},
        {"id": 6, "name": "A6", "building": "Studium 6"},
        {"id": 7, "name": "A7", "building": "Studium 6"},
    ]

    for row in data:
        Room.objects.create(**row)


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
