# Generated by Django 5.2.4 on 2025-07-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="speakers/"),
        ),
    ]
