# Generated by Django 5.2.4 on 2025-07-17 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0002_speaker_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={
                "ordering": ["name"],
                "verbose_name": "Speaker",
                "verbose_name_plural": "Speakers",
            },
        ),
    ]
