# Generated by Django 5.2.4 on 2025-08-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0003_alter_speaker_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="bio",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
