# Generated by Django 5.2.4 on 2025-08-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0004_speaker_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
